apiVersion: v1
kind: ReplicationController
metadata:
  name: node-api
spec:
  replicas: 3
  selector:
    app: node-api
  template:
    metadata:
      name: node-api
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: 191618872039.dkr.ecr.ap-southeast-2.amazonaws.com/bootcamp/node-api:4c9dd59
        ports:
        - containerPort: 3000
